### ISSUE TITLE
Deprecate this repository

### ISSUE THREAD

**Issue by krzkaczor** [amiorin/grunt-watchify#14]
Since grunt-browserify has option to watch sources and use watchify I would vote to mark this plugin as deprecated. I have wasted today about 1 hour trying to get it working when I could just add ```watch``` option to my current grunt-browserify task. My idea is to add clear, message about state of this project in readme. I can create PR for this. What do you think about it guys? @amiorin

**Comment by amiorin** [comment]
Sorry about that. I've done myself.
